config/routes.rb
Rails.application.routes.draw do

  post "students/:id/send_schedule_mail" => "students#send_schedule_mail"
  resources :schedules

  resources :students
  
  root 'students#index'

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
	
	############## Validations ########
	 	validates :start_date,:end_date, :start_time,:end_time, :location, :faculty,:course,:student_id,presence: true

	############## Associations ########
		belongs_to :student

	######################## Schema Information ################
	#
	# Table Name: schedules
	# 
	# integer  "student_id"
	# string   "course",     limit: 160, default: "", null: false
	# date     "start_date"
	# date     "end_date"
	# time     "start_time"
	# time     "end_time"
	# string   "location",               default: "", null: false
	# string   "faculty"
end

app/models/student.rb
class Student < ActiveRecord::Base
  
  ############# Scopes ##############
    scope :active, -> { where(deleted: false,status: 1) }
    scope :inactive, -> { where(status: 0,deleted: false) }  
    scope :deleted, -> { where(deleted: true) } 

  ############## Enums ##############
    enum gender: { :male => "0", :female => "1" }
    enum status: [ :active, :inactive ]

  ############## Validations ########
    validates :email,format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/, message: "Invalid email format" } , uniqueness: true,length: { in: 0..60}, on: :create
    validates :first_name,:last_name,:username,presence: true, length: { in: 0..30 }
    validates :gender, inclusion: { in: ['male', 'female'] }
    validates :status, inclusion: { in: ['active', 'inactive'] }
    validates :username, uniqueness: true, on: :create
    validates :student_number,uniqueness: true,length: { in: 0..20 }
    validates :postcode, length: { in: 0..10} 
    validates :address_1,:address_2, length: { in: 0..255}
    validates :city,:country, length: { maximum: 50, too_long: "%{count} characters is the maximum allowed" }  

  ############## Associations ########
    has_many :schedules

  mount_uploader :profile_picture, AvatarUploader

  ############## Methods ############
  	def initialize(attributes=nil, *args)
      super    
      self.student_number = Student.next_student_number
    end
    
    def self.next_student_number    
      p = Student.order('created_at DESC').first
      p.present? ? p.student_number.to_s.succ : "SD-001"
    end  

    def soft_delete!
      update_attribute(:deleted, true)
    end

end

######################## Schema Information ################
#
# Table Name: students
#
# string   "student_number",  limit: 20, default: "",    null: false
# string   "username",        limit: 30, default: "",    null: false
# string   "first_name",      limit: 30, default: "",    null: false
# string   "last_name",       limit: 30, default: "",    null: false
# string   "profile_picture"
# string   "gender"
# date     "dob"
# string   "email",           limit: 60, default: "",    null: false
# string   "address_1",                  default: "",    null: false
# string   "address_2",                  default: "",    null: false
# string   "city",            limit: 50
# string   "country",         limit: 50
# string   "postcode",        limit: 10, default: "",    null: false
# integer  "status",                     default: 0,     null: false
# boolean  "deleted",                    default: false, null: false
# datetime "created_at",                                 null: false
# datetime "updated_at",                                 null: false

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  # rescue_from ActiveRecord::RecordNotFound,Exception,ActiveRecord::ActiveRecordError,StandardError do |exception|
  #   redirect_to root_url, :alert => exception.message
  # end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :find_schedule, only: [:show, :edit, :update, :destroy]
  
  def index
    @schedules = Schedule.all    
  end
  
  def show;  end

  def new
    if params[:student_id].present?
      @schedule = Schedule.new(:student_id => params[:student_id])
    else
      redirect_to @schedule, alert: 'Unauthorized acesss'      
    end
  end

  def edit;  end

  def create
    @schedule = Schedule.new(schedule_params)
    if @schedule.save
      redirect_to @schedule.student, notice: 'Schedule was successfully created.'
    else
      # redirect_to @schedule.student, notice: 'Please fill all the fields correctly.'
      params[:student_id] = @schedule.student
      render :new, alert: 'Please fill all the fields correctly.'
    end    
  end

  def update
    if @schedule.update(schedule_params)
      redirect_to @schedule.student, notice: 'Schedule was successfully updated.'
    else
      render :edit
    end    
  end

  def destroy
    @schedule.destroy
    redirect_to @schedule.student, notice: 'Schedule was successfully destroyed.'
  end

  private
    
    def find_schedule
      @schedule = Schedule.find(params[:id])
      rescue ActiveRecord::RecordNotFound
			  flash[:notice] = "Record not found."
			  redirect_to :action => 'index'
    end

    
    def schedule_params
      params.require(:schedule).permit(:student_id, :course, :start_date, :end_date, :start_time, :end_time, :location, :faculty)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :find_student, only: [:show, :edit, :update, :destroy,:send_schedule_mail]
  
  def index
    @students = Student.active.paginate(:page => params[:page], :per_page => 5)    
  end
  
  def show
    @student.schedules
  end

  def new
    @student = Student.new
  end

  def edit;  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to @student, notice: 'Student was successfully created.'
    else
      render :new
    end    
  end

  def update
    if @student.update(student_params)
      redirect_to @student, notice: 'Student was successfully updated.'
    else
      render :edit
    end    
  end

  def destroy
    @student.soft_delete!
    redirect_to students_url, notice: 'Student was successfully destroyed.'
  end

  def send_schedule_mail
    if params[:email].present?
      StudentMailer.student_schedule(@student,params[:email]).deliver 
      redirect_to @student, notice: 'Email sent successfully.'
    else
      redirect_to @student, alert: 'Enter valid email.'
    end
  end

  private
    
    def find_student
      @student = Student.active.find(params[:id])
      rescue ActiveRecord::RecordNotFound
			  flash[:notice] = "Record not found."
			  redirect_to :action => 'index'
    end

    
    def student_params
      params.require(:student).permit(:username, :first_name, :last_name, :email, :gender, :dob, :address_1, :address_2, :city, :country, :postcode, :profile_picture, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0" />
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
	<title>StudentCare</title>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
<div class="main-container">
    <div class="container">
      <%= link_to(image_tag("logo.gif", :alt => "home image", :title => "Click here to return to Home"),root_path) %>
      <div class="row">
        <div class="col-md-12">
        	<div class="main-content">
        		<%= yield %>
          </div>
        </div>
      </div>
    </div>
</div>
</body>
</html>

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  
  <div class="row">
    <div class="col-md-6">
      <div class="input-box">
        <br>
        <div class="custom-select-box style-1">
          <%= f.select :student_id , Student.all.map{|student| ["#{student.username} (#{student.student_number})",student.id] }, :prompt => "Select a Student",:class => "form-control" %>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="input-box"> <i class="sprite icn-user"></i>
        <%#= f.label :course %><br>
        <%= f.text_field :course, :placeholder => "Course" %>
      </div>
    </div>
  </div>
 
  <div class="row">
    <div class="col-md-6">
      <div class="input-box"> <i class="sprite icn-user"></i>
        <%#= f.label :start_date %><br>
        <%= f.text_field :start_date, :placeholder => "Start Date" ,class: "datepicker"%>
      </div>
    </div>
    <div class="col-md-6">
      <div class="input-box"> <i class="sprite icn-user"></i>
        <%#= f.label :end_date %><br>
        <%= f.text_field :end_date, :placeholder => "End Date" ,class: "datepicker"%><br><br>
      </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-md-6">
      <div class="input-box"> <i class="sprite icn-user"></i>
        <%#= f.label :start_time %><br>
        <%= f.text_field :start_time, :placeholder => "Start Time" %><br><br>
      </div>
    </div>
    <div class="col-md-6">
      <div class="input-box"> <i class="sprite icn-user"></i>
        <%#= f.label :end_time %><br>
        <%= f.text_field :end_time, :placeholder => "End Time" %><br><br>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="input-box"> <i class="sprite icn-user"></i>
        <%#= f.label :location %><br>
        <%= f.text_field :location, :placeholder => "Location" %><br><br>
      </div>
    </div>
    <div class="col-md-6">
      <div class="input-box"> <i class="sprite icn-user"></i>
        <%#= f.label :faculty %><br>
        <%= f.text_field :faculty, :placeholder => "Faculty" %><br><br>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="actions pull-right col-md-6">
      <%= f.submit  params[:action] == "new" ? "Create" : "Update" , :class => "submit" %>
    </div>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', student_path(:id =>  @schedule.student_id) %>

app/views/schedules/index.html.erb
<h1>Listing schedules</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= link_to 'Show', schedule %></td>
        <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
        <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<h1>New schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', student_path(:id =>  params[:student_id]), :class => "cmn-btn grey" %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>

app/views/students/_form.html.erb
<div class="form-container">
  <h2> Student <span>Please fill out details</span> </h2>
  <%= form_for @student do |f| %>  
    <% if @student.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@student.errors.count, "error") %> prohibited
          this student from being saved:
        </h2>
        <ul>
          <% @student.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row">
      <div class="col-md-6">
        <div class="input-box"> <i class="sprite icn-user"></i>
          <%= f.text_field :username, :placeholder => "Username" %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="input-box">
            Student Number: <%=  f.object.student_number %>          
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <div class="input-box"> <i class="sprite icn-user"></i>
          <%= f.text_field :first_name, :placeholder => "First Name" %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="input-box"> <i class="sprite icn-user"></i>
          <%= f.text_field :last_name, :placeholder => "Last Name" %>
        </div>
      </div>
    </div>
    
    <div class="row">
      <div class="col-md-6 gender-field">
        <%= f.label :gender %>
          <div class="custom-opt">
              <label class=""><%= f.radio_button :gender, 'male' %>Male</label>
              <label class=""><%= f.radio_button :gender, 'female' %>Female</label>
          </div>
      </div>
      <div class="col-md-6">
        <div class="input-box">
            <div class="date-of-birth"><%= f.text_field :dob, :placeholder => "Date Of Birth", class: "datepicker" %><i class="sprite icn-choosedate"></i></div>
          </div>
      </div>
    </div>
    
    <div class="row">
      <div class="col-md-6">
        <div class="input-box">
            <%= f.text_area :address_1, :placeholder => "Address1" %>            
        </div>
      </div>
      <div class="col-md-6">
        <div class="input-box profile-img">
            <div id="preview-box">
            <%= image_tag(@student.profile_picture.url(:thumb),class: "no-image") %>
          </div>
          <div class="file-button">  <%=f.file_field :profile_picture%> Upload Image</div>                        
           </div>
      </div>
    </div>
    
    <div class="row">
      <div class="col-md-6">
        <div class="input-box"> <i class="sprite icn-user"></i>
          <%= f.text_field :address_2, :placeholder => "Address2" %>          
        </div>
      </div>
      <div class="col-md-6">
        <div class="input-box"> <i class="sprite icn-user"></i>
          <%= f.text_field :postcode, :placeholder => "Postal Code" %>
        </div>
      </div>
    </div>
    
    <div class="row">
      <div class="col-md-6">
      <div class="input-box"> <i class="sprite icn-user"></i>
        <%= f.text_field :city, :placeholder => "City" %>        
      </div>
      </div>
      <div class="col-md-6">
      <div class="input-box"> <i class="sprite icn-user"></i>
        <%= f.text_field :country, :placeholder => "Country" %>        
      </div>
      </div>
    </div>
    
    <div class="row">
      <div class="col-md-6">
        <div class="input-box"> <i class="sprite icn-email"></i>
          <%= f.email_field :email, :placeholder => "Email" %>
        </div>
      </div>
      <div class="col-md-6 gender-field">
        <label class="">Status:</label>
          <div class="custom-opt">
              <%#= f.select :status, Student.statuses.keys %>
              <label class=""><%= f.radio_button :status, 'active' %>Active</label>
              <label class=""><%= f.radio_button :status, 'inactive' %>Inactive</label>
          </div>
      </div>                
    </div>                
    
    <div class="row">
      <div class="col-md-12">
      <%= f.submit "#{@student.new_record? ? 'Add' : 'Update'} Student", :class => "submit pull-right" %>    
      </div>
    </div>
  <% end %>
</div>




<script>
  // Privew Image
  var avatar = $("#student_profile_picture");
  avatar[0].addEventListener("change",previewImages,false); //bind the function to the input
  function previewImages(){
    var fileList = this.files;    
    var anyWindow = window.URL || window.webkitURL;
    var objectUrl = anyWindow.createObjectURL(fileList[0]);    
    $('#preview-box').html('<img class="profileimg" src="' + objectUrl + '" /> ');
  }
</script>

app/views/students/edit.html.erb
<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<div class="form-container">
  <h2> Students Listing <span></span> </h2>
  <%= link_to 'Add New Student', new_student_path, :class => "submit pull-right" %>
  <div class="clearfix"></div>

  <div class="inner-action">
    <div class="row">
      <div class="col-sm-7">&nbsp;</div>
      <div class="col-sm-2">        
      </div>
    </div>
   </div>
   
  <div class="clearfix"></div>
  
  <div class="row">
    <div class="col-md-12">
      <div class="user-listing">
            <table class="responsive">
                <tbody><tr>
                    <!-- <th width="10px">
                        <div class="custom-chk">
                            <label class=""><input name="Gorilla" type="checkbox"></label>
                        </div>
                    </th> -->
                    <th>Student&nbsp;Number</th>
                    <th>Username</th>
                    <th>First&nbsp;Name</th>
                    <th>Last&nbsp;Name</th>
                    <th>Email</th>
                    <th>Gender</th>
                    <th>DOB</th>
                    <th>City</th>
                    <th>Country</th>
                    <th>Status</th>
                    <th colspan="3">Actions</th>
                </tr>
                <% @students.each do |student| %>
                  <tr>
                    <!-- <td>&nbsp;</td> -->
                    <td><%= student.student_number %></td>
                    <td><%= student.username %></td>
                    <td><%= student.first_name %></td>
                    <td><%= student.last_name %></td>
                    <td><%= student.email %></td>
                    <td><%= student.gender %></td>
                    <td><%= student.dob %></td>
                    <td><%= student.city %></td>
                    <td><%= student.country %></td>
                    <td><%= student.status %></td>
                    <td><%= link_to 'Show', student_path(student) %></td>
                    <td><%= link_to 'Edit', edit_student_path(student) %></td>
                    <td><%= link_to 'Delete', student_path(student),
                            method: :delete,
                            data: { confirm: 'Are you sure?' } %></td>
                  </tr>
                <% end %>               
            </tbody>
            </table>
            <%= will_paginate @students %>
<!--             <nav class="client-list-pagination">
              <ul class="pagination pull-right">
                <li class="disabled">
                  <a href="#" aria-label="Previous">
                    <span aria-hidden="true">«</span>
                  </a>
                </li>
                <li><a href="#">1</a></li>
                <li class="active"><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li>
                  <a href="#" aria-label="Next">
                    <span aria-hidden="true">»</span>
                  </a>
                </li>
              </ul>
            </nav> -->
        </div>
    </div>
  </div>                  
</div>

app/views/students/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<div class="form-container">
  <h2> Student Details <span>Access your Account Details</span> </h2>

  <div class="form-data user-detail">
    <div class="row">
      <div class="col-md-9">
        <%= image_tag(@student.profile_picture.url(:thumb),class: "pro-pic") %>
        <div class="user-contact-detail">
            <h3><%="#{@student.first_name} #{@student.last_name}" %></h3> 
            <p class="email"><%= @student.email %></p>
        </div>    
      </div>  

      <div class="col-md-3 text-right">
        <div class="user-detail-status">
          <p><span>Username:</span> <span class="status-value"><%= @student.username %></span></p>
          <p><span>Status:</span> <span class="status-value"><%= @student.status %></span></p>
          <p><span>Student Number:</span> <span class="status-value"><%= @student.student_number %></span></p>                        
        </div>  
      </div>  
    </div>  


  <div class="row">
      <div class="col-md-6">
        <span class="user-detail-label">Gender:</span>
        <span class="user-detail-value"><%= @student.gender %></span>
      </div>

      <div class="col-md-6">
        <span class="user-detail-label">Dob:</span>
        <span class="user-detail-value"><%= @student.dob %></span>
      </div>
   </div>
  <div class="row">
    <div class="col-md-6">
      <span class="user-detail-label">Address 1:</span>
      <span class="user-detail-value"><%= @student.address_1 %></span>
    </div>

    <!-- <div class="col-md-6">
      <span class="user-detail-label">Address 2:</span>
      <span class="user-detail-value"><%= @student.address_2 %></span>
    </div> -->

    <div class="col-md-6">
      <span class="user-detail-label">City:</span>
      <span class="user-detail-value"><%= @student.city %></span>
    </div>
  </div>    

  <div class="row">
    <div class="col-md-6">
      <span class="user-detail-label">Country:</span>
      <span class="user-detail-value"><%= @student.country %></span>
    </div>

    <div class="col-md-6">
      <span class="user-detail-label">Post code:</span>
      <span class="user-detail-value"><%= @student.postcode %></span>
    </div>
  </div>
</div>
<h3>Email this Shedule</h3>
<div class="row">
  <div class="pull-left">
    <%= form_tag({:action=>"send_schedule_mail"}, method: "post") do %>
      <%= hidden_field_tag :id,@student.id %>
      <div class="col-md-6">
        <div class="input-box"> <i class="sprite icn-email"></i>
          <%= text_field_tag :email,params[:email] ,placeholder: "Enter Email" , class: "input-xlarge",:size=>"50"%>
        </div>
      </div>
      <div class="col-md-6">
        <%= submit_tag "Send" ,:class=>"submit-form btn btn-success" %>                             
      </div>
    <% end %>
  </div>

  <% if flash[:notice]  %>
    <div class="pull-left"><div class="alert alert-success"><%= flash[:notice] %></div></div>
  <% end %>  
  <% if flash[:alert]  %>
    <div class="pull-left"><div class="alert alert-danger"><%= flash[:alert] %></div></div>
  <% end %>  
</div>
<% if @student.schedules.present? %>
  <div class="row user-schedule">
    <div class="col-md-12">
        <div class="inner-grey-title">
          <h5>Schedules <span class="title-notify"><%= @student.schedules.count %></span></h5>
        </div>
        <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Course</th>
                  <th>Start&nbsp;Date</th>
                  <th>End Date</th>
                  <th>Start Time</th>
                  <th>End Time</th>
                  <th>Location</th>
                  <th>Faculty</th>
                  <th>Delete</th>
                  <th>Edit</th>
                </tr>
              </thead>  
              <tbody>
                <% @student.schedules.each do |schedule| %>
                  <tr>
                    <td> <%= schedule.course %></td>
                    <td> <%= schedule.start_date %></td>
                    <td> <%= schedule.end_date %></td>
                    <td> <%= schedule.start_time.strftime("%H:%M %p") if schedule.start_time.present? %></td>
                    <td> <%= schedule.end_time.strftime("%H:%M %p") if schedule.end_time.present? %></td>
                    <td> <%= schedule.location %></td>
                    <td> <%= schedule.faculty %></td>
                    <td align="center"><%= link_to 'Delete', schedule_path(schedule),
                          method: :delete,
                          data: { confirm: 'Are you sure?' } %></td>
                    <td><%= link_to 'Edit', edit_schedule_path(schedule) %> </td>      
                  </tr>
               <% end %>      
             </tbody>
            </table>
          </div>
        </div>
      </div>      
<% else %> 
  <p>  No schedules created yet! </p>
<% end %> 

 <div class="row">
    <div class="col-md-12">
      <div class="button-group pull-left">
        <%= link_to 'Back', students_path, :class => 'cmn-btn grey' %>
      </div>
        <div class="button-group pull-right"> 
            <%= link_to 'Add Schedule', new_schedule_path(:student_id => @student.id),:class => 'cmn-btn purple' %>
            <%= link_to 'Edit', edit_student_path(@student), :class => 'cmn-btn grey' %> 
        </div>
      </div>
    </div>
</div>